'use strict'

const shimIterator = require('./Iterator/shim')
const shimIteratorFrom = require('./Iterator.from/shim')
const shimIteratorProto = require('./Iterator.prototype/shim')
const shimIteratorCtor = require('./Iterator.prototype.constructor/shim')
const shimIteratorDrop = require('./Iterator.prototype.drop/shim')
const shimIteratorEvery = require('./Iterator.prototype.every/shim')
const shimIteratorFilter = require('./Iterator.prototype.filter/shim')
const shimIteratorFind = require('./Iterator.prototype.find/shim')
const shimIteratorFlatMap = require('./Iterator.prototype.flatMap/shim')
const shimIteratorForEach = require('./Iterator.prototype.forEach/shim')
const shimIteratorMap = require('./Iterator.prototype.map/shim')
const shimIteratorReduce = require('./Iterator.prototype.reduce/shim')
const shimIteratorSome = require('./Iterator.prototype.some/shim')
const shimIteratorTake = require('./Iterator.prototype.take/shim')
const shimIteratorToArray = require('./Iterator.prototype.toArray/shim')

module.exports = function shimIteratorHelpers() {
  shimIterator()
  shimIteratorFrom()
  shimIteratorProto()
  shimIteratorCtor()
  shimIteratorDrop()
  shimIteratorEvery()
  shimIteratorFilter()
  shimIteratorFind()
  shimIteratorFlatMap()
  shimIteratorForEach()
  shimIteratorMap()
  shimIteratorReduce()
  shimIteratorSome()
  shimIteratorTake()
  shimIteratorToArray()
}
